spring.application.name=cs251-backend
server.port = 8080


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Optional: H2 web console at localhost:8080/h2-console
spring.h2.console.enabled=true

spring.http.encoding.enabled=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.mvc.charset=UTF-8
spring.web.encoding.charset=UTF-8

